services:
  - type: web
    name: aqb-api
    runtime: docker
    plan: free
    dockerfilePath: apps/api/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: http://localhost:4200,https://localhost:4200,http://localhost:3000,https://yanki.space,http://yanki.space
      - key: DATABASE_URL
        fromDatabase:
          name: aqb-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: AQB <onboarding@yanki.space>

databases:
  - name: aqb-postgres
    databaseName: aqb_production
    user: aqb_user
    plan: free
