services:
  - type: web
    name: aqb-api
    runtime: node
    plan: free
    buildCommand: npm install && npm install nx@21.3.11 && npm run api:build
    startCommand: npm run api:start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: aqb-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false

databases:
  - name: aqb-postgres
    databaseName: aqb_production
    user: aqb_user
    plan: free