name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build AQB application
        run: npx nx build aqb --configuration=production --base-href=https://yanki.space/

      - name: Replace build number
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const distPath = './dist/apps/aqb/browser';
            const configPath = path.join(distPath, 'assets', 'app-config.json');

            console.log('Updating build date...');

            // Check if the config file exists
            if (fs.existsSync(configPath)) {
              fs.readFile(configPath, 'utf8', function (err, data) {
                  if (err) {
                    console.log('Config file not found, skipping build date update');
                    return;
                  }

                  const result = data.replace("$BUILD_DATE$", new Date().toISOString())
                                     .replace("http://localhost:3000", "https://aqb-api.onrender.com");

                  fs.writeFile(configPath, result, 'utf8', function (err) {
                      if (err) return console.log(err);
                      console.log('Build date updated successfully');
                  });
              });
            } else {
              console.log('Config file not found at:', configPath);
            }

      - name: Create CNAME file
        run: echo "yanki.space" > ./dist/apps/aqb/browser/CNAME

      - name: Verify CNAME file
        run: |
          if [ -f "./dist/apps/aqb/browser/CNAME" ]; then
            echo "CNAME file created successfully"
            cat ./dist/apps/aqb/browser/CNAME
          else
            echo "ERROR: CNAME file not found"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/apps/aqb/browser'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
